import os
from typing import Any, Dict, Optional

from openai import AsyncOpenAI


class LLMGateway:
    """
    Central gateway for all LLM calls.

    Responsibilities:
    - Initialize the LLM client.
    - Apply model configuration.
    - Send prompts to the configured provider.
    - Return the raw text response.

    The gateway does not:
    - Build prompts.
    - Parse JSON.
    - Validate Pydantic models.
    - Contain agent-specific business logic.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        base_url: Optional[str] = None,
        default_model: Optional[str] = None,
    ) -> None:

        self.api_key = (
            api_key
            or os.getenv("LLM_API_KEY")
            or os.getenv("OPENAI_API_KEY")
        )

        self.base_url = (
            base_url
            or os.getenv("LLM_BASE_URL")
        )

        self.default_model = (
            default_model
            or os.getenv(
                "LLM_MODEL",
                "gpt-4o-mini",
            )
        )

        if not self.api_key:
            raise ValueError(
                "LLM API key is not configured. "
                "Set LLM_API_KEY or OPENAI_API_KEY."
            )

        client_kwargs: Dict[str, Any] = {
            "api_key": self.api_key,
        }

        if self.base_url:
            client_kwargs["base_url"] = self.base_url

        self.client = AsyncOpenAI(**client_kwargs)

    async def generate(
        self,
        prompt: str,
        **model_config: Any,
    ) -> str:
        """
        Send a prompt to the configured LLM.

        Returns:
            Raw text generated by the LLM.
        """

        config = dict(model_config)

        model = config.pop(
            "model",
            self.default_model,
        )

        response = await self.client.chat.completions.create(
            model=model,
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            **config,
        )

        return self._extract_content(response)

    @staticmethod
    def _extract_content(response: Any) -> str:
        """
        Extract text content from the OpenAI-compatible response.
        """

        if not response.choices:
            raise ValueError(
                "LLM returned no choices."
            )

        message = response.choices[0].message
        content = message.content

        if content is None:
            raise ValueError(
                "LLM returned an empty response."
            )

        return content.strip()